Repository bellshade/CPP, pull requests merged in 2022-10, with the labels that each got.

#55 feat: menambahkan materi umum struktur data
  struktur_data/README.md
Labels: Ok to merge, enhancement, HACKTOBERFEST-ACCEPTED

#57 Vector and function overload
  basic/16_Vector/README.md
  basic/16_Vector/vector_basic.cpp
  basic/17_function_overload/README.md
  basic/17_function_overload/function_overloading.cpp
Labels: good first issue, minor version, HACKTOBERFEST-ACCEPTED

#61 add: algoritma bubble sort pada doubly linked list
  algorithm/sorting/bubblesort_doubly_linkedlist.cpp
Labels: add, HACKTOBERFEST-ACCEPTED

#70 fix: memperbaiki dokumen readme
  .circleci/config.yml
  README.md
  basic/README.md
Labels: Ok to merge, bug, documentation, HACKTOBERFEST-ACCEPTED
